FROM postgres:14-alpine

WORKDIR /app

#RUN  -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=Qwerty100 -e POSTGRES_DB=gnupot_db -d -v "C:\Users\Рамиль\Desktop\docker-test-app\db_postgre\":/docker-entrypoint-initdb.d postgres:13.3